Complete task 4
Kenpachi2/-lesson1-2_task4_Umeadi-Ifeanyi pull request #1
Opened 2023-04-26 12:25 UTC by Kenpachi2

please kindly review @promise-j @ChidiPatrick

2023-04-26 12:37 UTC, promise-J requested changes
Please check your code. You are definitely doing something wrong

2023-04-26 12:37 UTC, promise-J commented on html/index.html
> +            <li>
From this line, you didn't nest your elements well. How can you put element li inside and outside. Please look at your code again

2023-04-26 18:18 UTC, Kenpachi2 commented on html/index.html
> +            <li>
Done. Can i merge now?

2023-05-02 11:14 UTC, promise-J approved these changes
You are cleared to move on to the next task

2023-05-02 12:04 UTC, merged